on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        perl-version: ['5.24', '5.26', '5.28', '5.30']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}

      - run: cpanm --installdeps .

      - run: cpanm git://github.com/utgwkk/Test2-Plugin-GitHub-Actions-AnnotateFailedTest.git@annotate-with-details

      - run: prove -Ilocal -Ilib -lv t
  